# This file was generated by GoReleaser. DO NOT EDIT.
class Bilocation < Formula
  desc "A tagging file system"
  homepage "https://github.com/corvus-ch/tagfuse"
  url "https://github.com/corvus-ch/bilocation/releases/download/v0.2.0/bilocation_0.2.0_darwin_amd64.tar.gz"
  version "0.2.0"
  sha256 "07ab70bf45922cee81986c56d29445996bc9c74e3c7cfd288d2df6e2e54bc31a"

  def install
    bin.install "bilocation"
  end
end
