# This file was generated by GoReleaser. DO NOT EDIT.
class Bilocation < Formula
  desc "A tagging file system"
  homepage "https://github.com/corvus-ch/tagfuse"
  url "https://github.com/corvus-ch/bilocation/releases/download/v0.2.1/bilocation_0.2.1_darwin_amd64.tar.gz"
  version "0.2.1"
  sha256 "c868ccbb586d84dc70b04aff8cb4d94010ace19124888896ec6cbcac8820d0fe"

  def install
    bin.install "bilocation"
  end
end
