# This file was generated by GoReleaser. DO NOT EDIT.
class Bilocation < Formula
  desc "A tagging file system"
  homepage "https://github.com/corvus-ch/tagfuse"
  url "https://github.com/corvus-ch/bilocation/releases/download/v0.2.1-alpha1/bilocation_0.2.1-alpha1_darwin_amd64.tar.gz"
  version "0.2.1-alpha1"
  sha256 "d8f58434d48596764a7fe96c473156519fdc9f5bc09a560cddda5ea414f79a93"

  def install
    bin.install "bilocation"
  end
end
