# This file was generated by GoReleaser. DO NOT EDIT.
class Horcrux < Formula
  desc "A helper for preparing backups of data worth protecting"
  homepage "https://github.com/corvus-ch/horcrux"
  url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.0/horcrux_1.3.0_darwin_amd64.tar.gz"
  version "1.3.0"
  sha256 "a8b58a5fcdcf4d3b17909a0b261f8769f7000d2a8d5ab64a0c5b70b0c7cb9096"

  def install
    bin.install "horcrux"
  end
end
