# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horcrux < Formula
  desc "A helper for preparing backups of data worth protecting"
  homepage "https://github.com/corvus-ch/horcrux"
  version "1.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.1/horcrux_1.3.1_darwin_amd64.tar.gz"
      sha256 "c06a9bf1354e2c020277615ff3daf07c222402c190e9cdee2f01bad1e77cca28"

      def install
        bin.install "horcrux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.1/horcrux_1.3.1_darwin_arm64.tar.gz"
      sha256 "f32f262f9fe2c23f21a2f568344fc9cf76c68df130f8e79be3e47468fbd8f6d1"

      def install
        bin.install "horcrux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.1/horcrux_1.3.1_linux_armv6.tar.gz"
      sha256 "d5bc40c385ff7370c3ef9df177b1fa338cb42b06692756f826cba99feebb8387"

      def install
        bin.install "horcrux"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.1/horcrux_1.3.1_linux_amd64.tar.gz"
      sha256 "d42cb0a8b5ad007d17143c6f4fe7fd416be4f4aedddc54c9dd4d56452c53a740"

      def install
        bin.install "horcrux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvus-ch/horcrux/releases/download/v1.3.1/horcrux_1.3.1_linux_arm64.tar.gz"
      sha256 "29fec17e5f6c153aac66b833755468cb3d4046bb66001689d2b8a60d20fcee65"

      def install
        bin.install "horcrux"
      end
    end
  end
end
